---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroutegrafana
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes: # change grafana.cno-user-XX-i-0X.commandemy.training to your host DNS
    - match: Host(`grafana.cno-user-XX-i-0X.commandemy.training`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: grafana
          port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetlsgrafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: myresolver
  routes: # change grafana.cno-user-XX-i-0X.commandemy.training to your host DNS
    - match: Host(`grafana.cno-user-XX-i-0X.commandemy.training`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: grafana
          port: 3000
