apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-traefik-rules
  namespace: monitoring
spec:
  groups:
  - name: traefik.rules
    rules:
    - alert: TraefikHighHttp4xxErrorRateService
      expr: sum(rate(traefik_service_requests_total{code=~"4.*"}[3m])) by (service) / sum(rate(traefik_service_requests_total[3m])) by (service) * 100 > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Traefik high HTTP 4xx error rate service (instance {{ $labels.instance }})
        description: "Traefik service 4xx error rate is above 5%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
