version: "3.3"

services:

  api:
    build:
      context: .
    image: 12-factor-app:v0.1
    env_file: docker-compose.env
    environment:
      SERVICES: api
    networks:
      - internal
    ports:
      - 8181:3000

  products:
    build:
      context: .
    image: 12-factor-app:v0.1
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - mongo
    networks:
      - internal

# don't forget to update the docker-compose.env TRANSPORTER=nats://nats:4222
  nats:
    image: 'nats:2.1'
    ports:
      - 4222:4222 # not needed, can be removed
      - 6222:6222 # accessible on the internal network
      - 8222:8222 # ports might be a risk, open from host!
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal

networks:
  internal:

volumes:
  data:
